### ISSUE TITLE
PHP Warning: popen() has been disabled for security reasons

### ISSUE THREAD

**Issue by flanchegong** [hhxsv5/laravel-s#184]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
PHP 7.1.30 (cli) (built: Aug  5 2019 15:37:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    # Swoole
    Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0
Built => Aug  5 2019 15:47:42
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2s  28 May 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
    # Laravel
            "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "hhxsv5/laravel-s": "^3.5",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "php-ai/php-ml": "^0.8.0"

    | Software | Version |
    | --------- | --------- |
    | PHP | `TODO` |
    | Swoole | `TODO` |
    | Laravel/Lumen | `TODO` |

2. Detail description about this issue(error/log)

    PHP Warning:  popen() has been disabled for security reasons in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 278
PHP Warning:  pclose() expects parameter 1 to be resource, null given in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 285
PHP Warning:  file_get_contents(/data/wwwroot/default/zt-swoole/storage/laravels.json): failed to open stream: No such file or directory in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 272
PHP Notice:  Undefined index: server in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 123
PHP Notice:  Undefined index: server in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 123
PHP Notice:  Undefined index: server in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 131
[2019-08-28 17:08:48] [TRACE] Swoole is running, press Ctrl+C to quit.
PHP Notice:  Undefined index: server in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 137
PHP Notice:  Undefined index: laravel in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 137
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hhxsv5\LaravelS\LaravelS::__construct() must be of the type array, null given, called in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 137 and defined in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/LaravelS.php:47
Stack trace:
#0 /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php(137): Hhxsv5\LaravelS\LaravelS->__construct(NULL, NULL)
#1 /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/Console/Portal.php(56): Hhxsv5\LaravelS\Console\Portal->start()
#2 /data/wwwroot/default/zt-swoole/vendor/symfony/console/Command/Command.php(255): Hhxsv5\LaravelS\Console\Portal->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /data/wwwroot/default/zt-swoole/bin/laravels(160): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutp in /data/wwwroot/default/zt-swoole/vendor/hhxsv5/laravel-s/src/LaravelS.php on line 47

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
`php -i|grep disable_functions`
check the configuration item [disable_functions](https://www.php.net/manual/zh/ini.core.php#ini.disable-functions) in your php.ini.
