### ISSUE TITLE
创建websocket 服务报错

### ISSUE THREAD

**Issue by Insua** [hhxsv5/laravel-s#222]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
   +---------------------------+---------------------------------------+
| PHP                       | 7.1.32-1+ubuntu16.04.1+deb.sury.org+1 |
| Swoole                    | 4.4.5                                 |
| LaravelS                  | 3.6.1                                 |
| Laravel Framework [local] | 5.8.36                                |
+---------------------------+---------------------------------------+

2. Detail description about this issue(error/log)

   启动websocket 服务 报错

3. Some `reproducible` code blocks and `steps`

    ```PHP
  class WebSocketService implements WebSocketHandlerInterface
{

    public function __construct()
    {
    }

    public function onOpen(Server $server, Request $request)
    {
        // TODO: Implement onOpen() method.
    }

    public function onMessage(Server $server, Frame $frame)
    {
        //
    }

    public function onClose(Server $server, $fd, $reactorId)
    {
        // TODO: Implement onClose() method.
    }
}
    ```
swoole报错日志

```
ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught Error: Cannot instantiate interface Hhxsv5\LaravelS\Swoole\WebSocketHandlerInterface in /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:174
Stack trace:
#0 /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(103): Hhxsv5\LaravelS\Swoole\Server->getWebSocketHandler()
#1 [internal function]: Hhxsv5\LaravelS\Swoole\Server->Hhxsv5\LaravelS\Swoole\{closure}()
#2 /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/Illuminate/LogTrait.php(82): call_user_func_array(Object(Closure), Array)
#3 /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(104): Hhxsv5\LaravelS\LaravelS->callWithCatchException(Object(Closure))
#4 /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(118): Hhxsv5\LaravelS\Swoole\Server->Hhxsv5\LaravelS\Swoole\{closure}('onClose', Array)
#5 [internal function]: Hhxsv5\LaravelS\Swoole\Server->Hhxsv5\LaravelS\Swoole\{closure}(Object(Swoole\WebSocket\Server), 2, 11)
#6 /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/ in /var/www/zhsq/sszhsq_ws/vendor/hhxsv5/laravel-s/src/Swoole/Server.php on line 174
```

**Comment by Insua** [comment]
我错了配置文件写错了
