### ISSUE TITLE
does not exist, or permission denied

### ISSUE THREAD

**Issue by ykxiao** [hhxsv5/laravel-s#453]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3. |
    | Swoole | 4.5.11 |
    | Laravel/Lumen | 8.83.27 |

2. Detail description about this issue(error/log)

    什么原因启动后报错：does not exist, or permission denied.。但是访问偶尔会成功一次，后面就正常。是什么权限问题。报错也是一堆没有线索的错误。

3. Some `reproducible` code blocks and `steps`

    ```PHP
    #swoole logs
    [2023-07-18 18:45:10] local.ERROR: Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 [internal function]: spl_autoload_call()
#5 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct()
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()
#7 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Fou {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 [internal function]: spl_autoload_call()
#5 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct()
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()
#7 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Fou at /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578)
[stacktrace]
#0 {main}
"} 
[2023-07-18 18:45:10] production.ERROR: Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Collections/Collection.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): spl_autoload_call()
#5 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config()
#7 /var/www {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Collections/Collection.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): spl_autoload_call()
#5 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\\Foundation\\PackageManifest->config()
#7 /var/www at /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578)
[stacktrace]
#0 {main}
"} 
[2023-07-18 18:45:12] local.ERROR: Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Support/Facades/Artisan.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/mes-admin-api/routes/console.php(17): spl_autoload_call()
#5 /var/www/mes-admin-api/app/Console/Kernel.php(42): require('/var/www/mes-ad...')
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(316): App\Console\Kernel->commands()
#7 /var/www/mes-admin-api/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(95): Illuminate\Foundat {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Support/Facades/Artisan.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 /var/www/mes-admin-api/routes/console.php(17): spl_autoload_call()
#5 /var/www/mes-admin-api/app/Console/Kernel.php(42): require('/var/www/mes-ad...')
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(316): App\\Console\\Kernel->commands()
#7 /var/www/mes-admin-api/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(95): Illuminate\\Foundat at /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578)
[stacktrace]
#0 {main}
"} 
    ```

**Comment by ykxiao** [comment]
Swoole log:
`[2023-07-18 18:56:25 *2978.29]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: include(/var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Cookie/CookieServiceProvider.php): failed to open stream: Input/output error in /var/www/mes-admin-api/vendor/composer/ClassLoader.php:578
Stack trace:
#0 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(578): include()
#2 /var/www/mes-admin-api/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): spl_autoload_call()
#5 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(679): Illuminate\Foundation\Application->resolveProvider()
#6 /var/www/mes-admin-api/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illumi in /var/www/mes-admin-api/vendor/composer/ClassLoader.php on line 578
`

**Comment by hhxsv5** [comment]
执行composer dump-autoload试试
