### ISSUE TITLE
协程mysql下遇到的问题

### ISSUE THREAD

**Issue by yumotingfeng** [hhxsv5/laravel-s#58]
1. Tell us your PHP version(`php -v`)
7.2.6
`TODO`

2. Tell us your Swoole version(`php --ri swoole`)
4.0.0
`TODO`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)
5.5.33
`TODO`

4. Detail description about this issue(error/log)
error
`TODO`

5. Give us a `reproducible` code block and `steps`

```PHP
//TODO: Your code
```
使用协程mysql普通业务逻辑查询，大概有6人同时使用
local.ERROR: Swoole\Coroutine\MySQL::prepare(): mysql client is waiting response, cannot send new sql query. (SQL: select `did` from `sys_district` where `pk_corp` = 1121 and `sys_district`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Swoole\\Coroutine\\MySQL::prepare(): mysql client is waiting response, cannot send new sql query. (SQL: select `did` from `sys_district` where `pk_corp` = 1121 and `sys_district`.`deleted_at` is null limit 1) at /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): Swoole\\Coroutine\\MySQL::prepare(): mysql client is waiting response, cannot send new sql query. at /data/nginx/pm-api/vendor/hhxsv5/laravel-s/src/Illuminate/Database/CoroutineMySQL.php:23)
[stacktrace]
#0 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `did` fr...', Array, Object(Closure))
#1 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `did` fr...', Array, Object(Closure))
#2 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1707): Illuminate\\Database\\Connection->select('select `did` fr...', Array, true)
#3 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1692): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(479): Illuminate\\Database\\Query\\Builder->get(Array)
#5 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(463): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#6 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#7 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(445): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#8 /data/nginx/pm-api/app/Http/Middleware/CheckSign.php(37): Illuminate\\Database\\Eloquent\\Builder->value('did')
#9 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckSign->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
"laravel-2018-07-04.log" 35410L, 6468760C
#39 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /data/nginx/pm-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 /data/nginx/pm-api/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(184): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 /data/nginx/pm-api/vendor/hhxsv5/laravel-s/src/LaravelS.php(165): Hhxsv5\\LaravelS\\Illuminate\\Laravel->handleDynamic(Object(Illuminate\\Http\\Request))
#48 /data/nginx/pm-api/vendor/hhxsv5/laravel-s/src/LaravelS.php(123): Hhxsv5\\LaravelS\\LaravelS->handleDynamicResource(Object(Illuminate\\Http\\Request), Object(Swoole\\Http\\Response))
#49 {main}
"}

**Comment by hhxsv5** [comment]
OK 晚上看看。

**Comment by hhxsv5** [comment]
Fixed in [65ed49e](https://github.com/hhxsv5/laravel-s/commit/65ed49e264562a833aa8def34199dce752df1eda).
