### ISSUE TITLE
大佬请教一下，启用WebSocket服务器后，WebSocketService无法获取客户端的websocket请求

### ISSUE THREAD

**Issue by HugBoomsj** [hhxsv5/laravel-s#74]
1. Tell us your PHP version(`php -v`)

` 7.2.6`

2. Tell us your Swoole version(`php --ri swoole`)

`swoole support => enabled
Version => 4.0.0
`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

`Laravel`

4. Detail description about this issue(error/log)

`artisan启动后一切正常就是无法在服务器端接受客户端的数据`

5. Give us a `reproducible` code block and `steps`

```
   // 声明没有参数的构造函数
    public function __construct()
    {
        Log::info('是否进入websocket');
    }
    public function onOpen(\swoole_websocket_server $server, \swoole_http_request $request)
    {

        // 在触发onOpen事件之前Laravel的生命周期已经完结，所以Laravel的Request是可读的，Session是可读写的
        \Log::info('New WebSocket connection', [$request->fd, request()->all(), session()->getId(), session('xxx'), session(['yyy' => time()])]);
        $server->push($request->fd, 'Welcome to LaravelS');
        // throw new \Exception('an exception');// 此时抛出的异常上层会忽略，并记录到Swoole日志，需要开发者try/catch捕获处理
    }
    public function onMessage(\swoole_websocket_server $server, \swoole_websocket_frame $frame)
    {
        \Log::info('Received message', [$frame->fd, $frame->data, $frame->opcode, $frame->finish]);
        $server->push($frame->fd, date('Y-m-d H:i:s'));
        // throw new \Exception('an exception');// 此时抛出的异常上层会忽略，并记录到Swoole日志，需要开发者try/catch捕获处理
    }

```

6.客户端JS
```

     var ws = new WebSocket("wss://chat.msjoo.cn/wss");
        ws.onopen = function (event) {
            console.log("Send Text WS was opened.");
        };
        ws.onmessage = function (event) {
            console.log("response text msg: " + event.data);
        };
        ws.onerror = function (event) {
            console.log("Send Text fired an error");
        };
        ws.onclose = function (event) {
            console.log("WebSocket instance closed.");
        };
```

Nginx 配置文件都是粘贴复制的

**Comment by hhxsv5** [comment]
1.确认客户端是否连接成功，连接时有无错误信息
2.注意到使用了`wss`，Nginx配置ssl了吗？

**Comment by HugBoomsj** [comment]
ssl用的腾讯云的官方的配置文件，以前还在小程序里面做过聊天室都是可以的。
另外[websocket线上测试工具](http://www.blue-zero.com/WebSocket/)我用了在线的测试工具
```

你 17:49:52
等待服务器握手包...
你 17:49:52
收到服务器握手包.
服务器 17:49:52
连接已建立，正在等待数据...

```
然后就一直等待数据，`class WebSocketService implements WebSocketHandlerInterface`  这个类是专门用来处理websocket请求，我是不是还差点啥QAQ

**Comment by hhxsv5** [comment]
尝试 直接在Chrome 控制台执行上面的JS代码
```Javascript
var ws = new WebSocket('wss://chat.msjoo.cn/wss');
ws.onopen = function(evt) { 
    console.log("Connection open ..."); 
    ws.send("Hello WebSocket!");
};
ws.onmessage = function(evt) {
    console.log('Received Message: ' + evt.data);
};
ws.onclose = function(evt) {
    console.log('Connection closed.');
};
```

观察其输出及错误信息

**Comment by HugBoomsj** [comment]
![2018-08-08 10 12 15](https://user-images.githubusercontent.com/24501722/43812405-c1186110-9af3-11e8-9234-b1d20ba6f27e.png)
```
等了一会就自动关闭了
```

**Comment by hhxsv5** [comment]
Nginx配置会影响心跳
```Nginx
# 如果60秒内被代理的服务器没有响应数据给Nginx，那么Nginx会关闭当前连接
proxy_read_timeout 60s;
```

**Comment by HugBoomsj** [comment]
我好像发现问题所在了
本地mac  测试启动

<img width="647" alt="2018-08-08 10 26 27" src="https://user-images.githubusercontent.com/24501722/43812802-92cf18d8-9af5-11e8-8b9d-0e62622d0c45.png">


PID[ ]  里面参数丢失了

**Comment by hhxsv5** [comment]
嗯，把storage中的laravels.pid删除，重新start试试。

**Comment by HugBoomsj** [comment]
我遇到了很群里一个小伙伴一样的问题。
我昨天是先创建了一个空的laravels.pid文件解决了报错。导致现在PID丢失参数
这个报错要咋整呢
```
LaravelS: PID file[/data/wwwroot/default/WssChat/storage/laravels.pid] does not exist.
```

**Comment by hhxsv5** [comment]
`ps -ef|grep laravels`找到master进程pid，kill掉

**Comment by HugBoomsj** [comment]
没有这个进程了
```
root     24023 19464  0 10:34 pts/3    00:00:00 grep --color laravels   
```

**Comment by HugBoomsj** [comment]
`drwxrwxrwx  5 git  git    4096 8月   8 10:30 storage  `  storage 给 777 也不好使

**Comment by hhxsv5** [comment]
那start就行了，如果依然提示不存在，则建立个空pid文件。

**Comment by HugBoomsj** [comment]
新建空文件laravels.pid  
启动后，PID参数为空，没有master进程
![2018-08-08 10 37 22](https://user-images.githubusercontent.com/24501722/43813201-2fbcf95c-9af7-11e8-9365-4c4f2e0ee49a.png)

**Comment by hhxsv5** [comment]
看看storage中的错误日志

**Comment by HugBoomsj** [comment]
这个好像不是的~~，我一开始直接用php artisan start 报错了。（这是所有的日志内容）
```
[2018-08-08 01:46:20] local.ERROR: Command "start" is not defined.

Did you mean this?
    queue:restart {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"start\" is not defined.

Did you mean this?
    queue:restart at /data/wwwroot/default/WssChat/vendor/symfony/console/Application.php:618)
[stacktrace]
#0 /data/wwwroot/default/WssChat/vendor/symfony/console/Application.php(229): Symfony\\Component\\Console\\Application->find('start')
#1 /data/wwwroot/default/WssChat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#2 /data/wwwroot/default/WssChat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /data/wwwroot/default/WssChat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /data/wwwroot/default/WssChat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"}

```

**Comment by hhxsv5** [comment]
swoole日志呢

**Comment by HugBoomsj** [comment]
swoole日志没有在logs里面生成者说明什么呀
![2018-08-08 10 55 42](https://user-images.githubusercontent.com/24501722/43813769-ad366ac4-9af9-11e8-8aeb-5241a2a5bc3c.png)


本地测试都ok
<img width="1096" alt="2018-08-08 10 56 29" src="https://user-images.githubusercontent.com/24501722/43813783-c5113ea8-9af9-11e8-9aab-b0303e145d6c.png">

**Comment by HugBoomsj** [comment]
总结一下：
1.最大的可能是线上服务器的问题
2.artisan启动监听，本次测试PID[68443] ,线上PID[ ]参数为空
3.ps查询压根没有laravels进程

**Comment by hhxsv5** [comment]
将laravels.php中`swoole.daemonize`设置为false，重新start，观察控制台输出。

**Comment by HugBoomsj** [comment]
老大，很感谢。
![2018-08-08 11 15 50](https://user-images.githubusercontent.com/24501722/43814387-b6062722-9afc-11e8-9777-dbeb11b04a85.png)
我刚刚重启了腾讯云，重新start之后端口都没用监听了

**Comment by hhxsv5** [comment]
升级Swoole到4.0.3试试。

**Comment by phpyii** [comment]
+---------------------------+------------------------------------------+
| Component                 | Version                                  |
+---------------------------+------------------------------------------+
| PHP                       | 7.1.7                                    |
| Swoole                    | 4.2.12                                   |
| LaravelS                  | 3.3.9                                    |
| Laravel Framework [local] | Lumen (5.7.7) (Laravel Components 5.7.*) |
+---------------------------+------------------------------------------+
我也复制的示例代码也有问题  只能握手 接收不到消息，最终发现是代码里记录日志的问题
把所有的 Log::info都注释掉就好了。
那么应该怎么记录日志？

**Comment by hhxsv5** [comment]
@phpyii 可能是Lumen没有开启Facade的原因，默认没有开启，手动打开试试。

```php
// bootstrap/app.php
$app->withFacades();
```

**Comment by phpyii** [comment]
@hhxsv5  打开了不行。
websocket会用到bootstrap/app.php里的配置吗？
http因为有public/index.php中
$app = require __DIR__.'/../bootstrap/app.php';
$app->run();
websocket  会先走这个吗？

**Comment by hhxsv5** [comment]
@phpyii 会走bootstrap，但不会走index，可以参考[源码](https://github.com/hhxsv5/laravel-s/blob/master/src/Illuminate/Laravel.php#L43)。

**Comment by phpyii** [comment]
@hhxsv5  ok 好了 谢谢！ 是我把log命名空间/去掉的问题

**Comment by phpyii** [comment]
还有个问题，为什么我在WebSocketService 写的onRequest不执行？
http的请求不能在socket中监听吗？

**Comment by hhxsv5** [comment]
laravel-s中如果启用WebSocket，那实际上laravel-s启动的是WebSocketServer，同时绑定了onRequest来支持Http协议。也就是说Http协议走Laravel的路由，WebSocket走WebSocketService里的事件处理，只不过是监听的同一个IP和Port，这两个都能用`http://127.0.0.1:5200` `ws://127.0.0.1:5200`。
